import { useCallback, useEffect, useMemo, useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import { MarketplacePrices } from './MarketplacePrices';
const base=(import.meta.env.VITE_FLOOR_FUNCTIONS_URL||'https://inventoryobi.netlify.app').replace(/\/$/,'');
type Channel={key:string;label:string;aliases:string[]};
const defaultChannels:Channel[]=[{key:'vendoo',label:'Vendoo',aliases:['vendoo']},{key:'ebay',label:'eBay',aliases:['ebay','e bay']},{key:'mercari',label:'Mercari',aliases:['mercari']},{key:'poshmark',label:'Poshmark',aliases:['poshmark']},{key:'facebook',label:'Facebook Marketplace',aliases:['facebook marketplace','facebook','meta']},{key:'depop',label:'Depop',aliases:['depop']},{key:'etsy',label:'Etsy',aliases:['etsy']},{key:'grailed',label:'Grailed',aliases:['grailed']},{key:'vinted',label:'Vinted',aliases:['vinted']},{key:'vestiaire_collective',label:'Vestiaire Collective',aliases:['vestiaire collective','vestiaire']},{key:'whatnot',label:'Whatnot',aliases:['whatnot']},{key:'shopify',label:'Shopify',aliases:['shopify']},{key:'other',label:'Other',aliases:[]}];
type Inv={sku:string;title:string|null;listed_on:string[];state:string;ask_cents:number|null;has_photo:boolean};
type Review={id:number;marketplace:string|null;subject:string|null;state:string;sku:string|null;item_title:string|null;order_number:string|null;sale_price_cents:number|null;ship_by:string|null;buyer:Record<string,string>;reason:string|null;created_at:string};
type Delist={id:number;sku:string;channel:string;created_at:string};
type ExportRow={sku:string;title:string;description:string;price_cents:number;condition:string|null;brand:string|null;category:string|null;photo_paths:string[];package_weight_lb:number|null;package_length_in:number|null;package_width_in:number|null;package_height_in:number|null;listed_on:string[];ebay_ok?:boolean;whatnot_ok?:boolean;depop_ok?:boolean;mercari_ok?:boolean;eligibility_notes?:string|null};
type EbayStatus={connected:boolean;username:string|null;connectedAt:string|null;lastSyncAt:string|null;lastError:string|null;ordersOnly:boolean;requiredUsername:string;disabled:boolean};
type Props={client:SupabaseClient;accessToken:string;money:(n:number)=>string;stamp?:(s:string)=>string};
const csv=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;
function saveCsv(name:string,rows:unknown[][]){const text='\uFEFF'+rows.map(r=>r.map(csv).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
async function ebayCall(token:string,action:string){const res=await fetch(`${base}/.netlify/functions/ebay-connection`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({action})});const body=await res.json().catch(()=>({}));if(!res.ok||body.ok===false)throw new Error(body.error||`eBay request failed (${res.status})`);return body as EbayStatus & {ok:boolean;url?:string;orders?:unknown};}
export function MarketplacesPage({client,accessToken,money,stamp}:Props){
 const [inv,setInv]=useState<Inv[]>([]),[review,setReview]=useState<Review[]>([]),[delists,setDelists]=useState<Delist[]>([]),[exp,setExp]=useState<ExportRow[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [channelOptions,setChannelOptions]=useState<Channel[]>(defaultChannels),[channelText,setChannelText]=useState('');
 const [ebay,setEbay]=useState<EbayStatus|null>(null);
 const channels=channelOptions.map(x=>x.key);
 const [sale,setSale]=useState<{sku:string;channel:string;price:string;order:string;fulfillment:string}|null>(null);
 const [reviewEdit,setReviewEdit]=useState<{row:Review;sku:string;channel:string;price:string}|null>(null);
 const loadEbay=useCallback(async()=>{try{setEbay(await ebayCall(accessToken,'status'));}catch(e){setEbay(null);setError(e instanceof Error?e.message:String(e));}},[accessToken]);
 async function load(){setError('');try{const [a,b,c,d,ch]=await Promise.all([client.rpc('portal_marketplace_inventory'),client.rpc('portal_marketplace_email_sales'),client.rpc('portal_marketplace_delists'),client.rpc('portal_vendoo_export'),client.rpc('portal_marketplace_channels')]);for(const x of [a,b,c,d,ch])if(x.error)throw x.error;setInv(a.data||[]);setReview((b.data||[]).filter((x:Review)=>x.state==='needs_review'));setDelists(c.data||[]);setExp(d.data||[]);const configured=(ch.data||defaultChannels) as Channel[];setChannelOptions(configured);setChannelText(configured.map(x=>x.key+' | '+x.label+' | '+x.aliases.join(', ')).join('\n'));await loadEbay();}catch(e){setError(e instanceof Error?e.message:String(e));}}
 useEffect(()=>{void load();},[]);
 async function listed(u:Inv,channel:string,checked:boolean){setBusy(true);try{const next=checked?[...new Set([...(u.listed_on||[]),channel])]:u.listed_on.filter(x=>x!==channel);const {error:e}=await client.rpc('portal_set_unit_listed_on',{p_sku:u.sku,p_channels:next});if(e)throw e;setNotice(`SKU ${u.sku} listing status saved.`);await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function sell(payload:Record<string,unknown>){setBusy(true);setError('');try{const res=await fetch(`${base}/.netlify/functions/marketplace-sale`,{method:'POST',headers:{Authorization:`Bearer ${accessToken}`,'content-type':'application/json'},body:JSON.stringify(payload)});const body=await res.json();if(!res.ok)throw new Error(body.error||`Request failed ${res.status}`);setNotice(`Sale recorded for SKU ${String(payload.sku)}. Floor will delist it from the website and other channels.`);setSale(null);setReviewEdit(null);await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function exportVendoo(){setBusy(true);try{const {data,error:e}=await client.rpc('portal_vendoo_export');if(e)throw e;const rows=(data||[]) as ExportRow[];setExp(rows);const depopBlocked=rows.filter(x=>x.depop_ok===false).length;saveCsv(`OpenBox-Vendoo-${new Date().toISOString().slice(0,10)}.csv`,[['Title','Description','Price','Condition','Brand','Category','Photo URLs','Weight lb','Length in','Width in','Height in','SKU','eBay OK','Whatnot OK','Depop OK','Mercari OK','Eligibility notes'],...rows.map(x=>[x.title,`${x.description.replace(/\s*SKU\s+\d{5}\s*$/i,'').trim()}\n\nSKU ${x.sku}`,(x.price_cents/100).toFixed(2),/sealed|new/i.test(x.condition||'')&&!/open|damage/i.test(x.condition||'')?'New':/open|box|package/i.test(x.condition||'')?'New with defects / Open box':'Used',x.brand,x.category,x.photo_paths.map(p=>`https://openboxindustries.com/media/${p.split('/').map(encodeURIComponent).join('/')}`).join(' | '),x.package_weight_lb,x.package_length_in,x.package_width_in,x.package_height_in,x.sku,x.ebay_ok?'YES':'NO',x.whatnot_ok?'YES':'NO',x.depop_ok?'YES':'NO',x.mercari_ok?'YES':'NO',x.eligibility_notes||''])]);setNotice(`Exported ${rows.length} items eligible on at least one Vendoo channel.${depopBlocked?` ${depopBlocked} are blocked on Depop — do not crosslist those to Depop.`:' '}Use the OK columns as the crosslist checklist.`)}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function done(id:number){setBusy(true);try{const {error:e}=await client.rpc('portal_complete_marketplace_delist',{p_id:id});if(e)throw e;await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function saveChannels(){setBusy(true);setError('');try{const rows=channelText.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const [key,label,aliases='']=line.split('|').map(x=>x.trim());return{key,label,aliases:aliases.split(',').map(x=>x.trim()).filter(Boolean)}});if(!rows.length)throw new Error('Keep at least one marketplace.');const {error:e}=await client.rpc('portal_set_online_setting',{p_key:'marketplace_channels',p_value:rows});if(e)throw e;setNotice('Marketplace list saved.');await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 const channelLabel=(key:string)=>channelOptions.find(x=>x.key===key)?.label||key;
 const counts=useMemo(()=>({listed:inv.filter(x=>x.listed_on?.length).length,review:review.length}),[inv,review]);
 return <><header><div><div className="eyebrow">SALES CHANNELS</div><h1>Marketplaces</h1><p>Connect eBay for order sync (orders only — Vendoo owns listings). Export for Vendoo, record off-site sales, and clear delist reminders.</p></div><button className="secondary" onClick={()=>void load()}>Refresh</button></header>
 {error&&<div className="alert" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}{notice&&<div className="hint">{notice}<button className="text-button" onClick={()=>setNotice('')}>Dismiss</button></div>}
 <div className="stats"><div className="stat"><span>Units listed elsewhere</span><strong>{counts.listed}</strong></div><div className="stat"><span>Sales to review</span><strong>{counts.review}</strong></div><div className="stat"><span>Delist reminders</span><strong>{delists.length}</strong></div></div>
 <section className="panel"><h2>eBay connection</h2>
  <p>Floor only reads sales and can mark shipped. It will never create, revise, or end eBay listings. Only <strong>{ebay?.requiredUsername || 'pgg124-5'}</strong> is accepted.</p>
  {ebay?.disabled ? <div className="alert" role="alert">eBay is fully disabled in Netlify (EBAY_DISABLED). Ask an operator to turn that off.</div> : <>
   <p>{ebay?.connected ? <>Connected as <strong>{ebay.username || 'unknown'}</strong>{ebay.connectedAt && stamp ? <> · since {stamp(ebay.connectedAt)}</> : null}{ebay.lastSyncAt && stamp ? <> · last sync {stamp(String(ebay.lastSyncAt))}</> : <> · not synced yet</>}</> : 'eBay is not connected.'}</p>
   {ebay?.lastError && <p className="hint">Last error: {ebay.lastError}</p>}
   <div className="actions">
    {!ebay?.connected && <button disabled={busy} onClick={()=>void (async()=>{setBusy(true);setError('');try{const data=await ebayCall(accessToken,'connect');if(data.url)window.location.href=data.url;}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}})()}>Connect eBay</button>}
    {ebay?.connected && <button className="secondary" disabled={busy} onClick={()=>void (async()=>{setBusy(true);setError('');try{const data=await ebayCall(accessToken,'sync_now');setEbay(data);setNotice(`Sync finished${Array.isArray(data.orders)?` · ${data.orders.length} result(s)`:''}. Check the Orders tab.`);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}})()}>Sync orders now</button>}
    {ebay?.connected && <button className="text-button danger" disabled={busy} onClick={()=>{if(!window.confirm('Disconnect eBay? Order sync will stop until you reconnect pgg124-5.'))return;void (async()=>{setBusy(true);try{setEbay(await ebayCall(accessToken,'disconnect'));setNotice('eBay disconnected.');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}})();}}>Disconnect</button>}
   </div>
  </>}
 </section>
 <section className="panel"><h2>Export for Vendoo</h2><p>Exports available units with photos and prices that are not already marked Vendoo, and that are eligible on at least one of eBay / Whatnot / Depop / Mercari. CSV includes per-channel OK flags — never enable Depop (or any other channel) when its column is NO.</p><button disabled={busy} onClick={()=>void exportVendoo()}>Export for Vendoo ({exp.length} ready)</button><p className="hint">Vendoo does not document generic CSV listing import. Treat this as a listing worksheet; post through Vendoo or its browser extension. Eligibility rules are edited under the Eligibility tab.</p></section>
 <section className="panel"><h2>Marketplace sales</h2><p>Sale emails with an exact SKU and price are processed automatically. Unmatched emails wait here; confirm SKU and price before Floor marks anything sold.</p>{review.length===0?<div className="empty">No emails waiting for review.</div>:<div className="ticket-list">{review.map(r=><div className="ticket" key={r.id}><strong>{r.marketplace||'Marketplace'} � {r.item_title||r.subject}</strong><small>{r.reason||'Needs review'} � Order {r.order_number||'unknown'} � {r.ship_by?`Ship by ${r.ship_by}`:'No ship-by date'}</small>{reviewEdit?.row.id===r.id?<div className="actions"><input aria-label="SKU" inputMode="numeric" value={reviewEdit.sku} onChange={e=>setReviewEdit({...reviewEdit,sku:e.target.value})} placeholder="Exact Floor SKU"/><select value={reviewEdit.channel} onChange={e=>setReviewEdit({...reviewEdit,channel:e.target.value})}>{channels.map(x=><option key={x}>{x}</option>)}</select><input aria-label="Sale price" type="number" min="0.01" step="0.01" value={reviewEdit.price} onChange={e=>setReviewEdit({...reviewEdit,price:e.target.value})}/><button disabled={busy} onClick={()=>void sell({action:'approve_review',review_id:r.id,sku:reviewEdit.sku,channel:reviewEdit.channel,price_cents:Math.round(Number(reviewEdit.price)*100)})}>Confirm sale</button><button className="secondary" onClick={()=>setReviewEdit(null)}>Cancel</button></div>:<button className="secondary" onClick={()=>setReviewEdit({row:r,sku:r.sku||'',channel:r.marketplace||'mercari',price:r.sale_price_cents==null?'':(r.sale_price_cents/100).toFixed(2)})}>Review & match</button>}</div>)}</div>}</section>
 <section className="panel"><h2>Units and listing status</h2><p>Mark which channels currently list each unit. �Mark sold� is a manual fallback that records the sale in Floor and opens delist reminders.</p><div className="ticket-list">{inv.map(u=><div className="ticket" key={u.sku}><div className="ticket-top"><strong>{u.title||`SKU ${u.sku}`}</strong><span>SKU {u.sku} � {u.state} � {u.ask_cents==null?'No price':money(u.ask_cents)}</span></div><div className="actions">{channels.map(c=><label key={c}><input type="checkbox" checked={u.listed_on?.includes(c)} disabled={busy} onChange={e=>void listed(u,c,e.target.checked)}/> {channelLabel(c)}</label>)}{u.state==='available'&&<button className="text-button danger" onClick={()=>setSale({sku:u.sku,channel:'mercari',price:(u.ask_cents?u.ask_cents/100:0).toFixed(2),order:'',fulfillment:'ship'})}>Mark sold�</button>}</div><MarketplacePrices sku={u.sku} accessToken={accessToken} client={client} money={money}/></div>)}</div></section>
 <section className="panel"><h2>Marketplace list</h2><p>One marketplace per line: key | display name | email keywords. This list powers listing checkboxes, sold-on choices, email matching, delist alerts, Vendoo export, and reports.</p><label className="notes">Channels<textarea rows={12} value={channelText} onChange={e=>setChannelText(e.target.value)}/></label><button disabled={busy} onClick={()=>void saveChannels()}>Save marketplace list</button></section>
 <section className="panel"><h2>Delist reminders</h2>{delists.length===0?<div className="empty">No open reminders.</div>:<div className="ticket-list">{delists.map(d=><div className="ticket ticket-top" key={d.id}><strong>SKU {d.sku} sold � delist in {d.channel}</strong><button disabled={busy} onClick={()=>void done(d.id)}>Done</button></div>)}</div>}</section>
 {sale&&<div className="modal-backdrop"><form className="panel modal" onSubmit={e=>{e.preventDefault();const cents=Math.round(Number(sale.price)*100);if(cents>0&&window.confirm(`Record SKU ${sale.sku} sold on ${channelLabel(sale.channel)} for ${money(cents)}? This marks it sold in Floor.`))void sell({sku:sale.sku,channel:sale.channel,price_cents:cents,order_number:sale.order,fulfillment:sale.fulfillment});}}><h2>Record marketplace sale � SKU {sale.sku}</h2><label>Marketplace<select value={sale.channel} onChange={e=>setSale({...sale,channel:e.target.value})}>{channels.map(x=><option key={x}>{x}</option>)}</select></label><label>Sale price ($)<input required type="number" min="0.01" step="0.01" value={sale.price} onChange={e=>setSale({...sale,price:e.target.value})}/></label><label>Order number<input value={sale.order} onChange={e=>setSale({...sale,order:e.target.value})}/></label><label>Fulfillment<select value={sale.fulfillment} onChange={e=>setSale({...sale,fulfillment:e.target.value})}><option value="ship">To ship</option><option value="pickup">Pickup</option></select></label><div className="actions"><button disabled={busy}>Confirm sold</button><button type="button" className="secondary" onClick={()=>setSale(null)}>Cancel</button></div></form></div>}
 </>;
}
