#!/usr/bin/env bash
# After `npx cap sync ios`: ensure Square Mobile Payments SDK is linked and buildable.
# CapApp-SPM is regenerated by cap sync from packages/square-plugin/Package.swift
# (which declares SquareMobilePaymentsSDK). This script hardens the Xcode project:
# deployment target, setup run script, plist keys, and verifies CapApp-SPM includes FloorSquare.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IOS="$ROOT/apps/adapter/ios"
PBX="$IOS/App/App.xcodeproj/project.pbxproj"
PLIST="$IOS/App/App/Info.plist"
SPM="$IOS/App/CapApp-SPM/Package.swift"
CFG="$IOS/App/App/capacitor.config.json"

if [ ! -f "$PBX" ] || [ ! -f "$PLIST" ]; then
  echo "iOS project missing; skip Square prepare" >&2
  exit 0
fi

sed_inplace() {
  if sed --version >/dev/null 2>&1; then
    sed -i "$@"
  else
    sed -i '' "$@"
  fi
}

# Square Mobile Payments SDK requires iOS 16+ (Package.swift); docs recommend 17.1+.
sed_inplace 's/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/IPHONEOS_DEPLOYMENT_TARGET = 16.0;/g' "$PBX"
sed_inplace 's/IPHONEOS_DEPLOYMENT_TARGET = 15;/IPHONEOS_DEPLOYMENT_TARGET = 16.0;/g' "$PBX"

# Setup script must run unsandboxed.
if grep -q "ENABLE_USER_SCRIPT_SANDBOXING" "$PBX"; then
  sed_inplace 's/ENABLE_USER_SCRIPT_SANDBOXING = YES;/ENABLE_USER_SCRIPT_SANDBOXING = NO;/g' "$PBX"
else
  sed_inplace 's/ENABLE_USER_SCRIPT_SANDBOXING = NO;/ENABLE_USER_SCRIPT_SANDBOXING = NO;/g' "$PBX"
  # Insert into both Debug/Release project-level build settings if missing.
  python3 - "$PBX" <<'PY'
from pathlib import Path
import re, sys
p = Path(sys.argv[1])
text = p.read_text()
if "ENABLE_USER_SCRIPT_SANDBOXING" not in text:
    text = text.replace(
        "buildSettings = {",
        "buildSettings = {\n\t\t\t\tENABLE_USER_SCRIPT_SANDBOXING = NO;",
        1,
    )
    # Also patch remaining buildSettings blocks that look like native target configs
    text = re.sub(
        r"(buildSettings = \{\n)(\t+)(ALWAYS_SEARCH_USER_PATHS)",
        r"\1\2ENABLE_USER_SCRIPT_SANDBOXING = NO;\n\2\3",
        text,
        count=4,
    )
    p.write_text(text)
print("user script sandboxing disabled (or already off)")
PY
fi

# Privacy keys for Square readers.
if [ -x /usr/libexec/PlistBuddy ]; then
  for key in NSBluetoothAlwaysUsageDescription NSBluetoothPeripheralUsageDescription \
             NSLocationWhenInUseUsageDescription NSMicrophoneUsageDescription; do
    /usr/libexec/PlistBuddy -c "Delete :$key" "$PLIST" 2>/dev/null || true
  done
  /usr/libexec/PlistBuddy -c "Add :NSBluetoothAlwaysUsageDescription string Floor uses Bluetooth to talk to the Square card reader." "$PLIST"
  /usr/libexec/PlistBuddy -c "Add :NSBluetoothPeripheralUsageDescription string Floor uses Bluetooth to talk to the Square card reader." "$PLIST"
  /usr/libexec/PlistBuddy -c "Add :NSLocationWhenInUseUsageDescription string Square needs location while taking a payment." "$PLIST"
  /usr/libexec/PlistBuddy -c "Add :NSMicrophoneUsageDescription string Some Square readers use the microphone for magstripe payments." "$PLIST"

  APP_ID="${SQUARE_APPLICATION_ID:-}"
  /usr/libexec/PlistBuddy -c "Delete :SquareApplicationID" "$PLIST" 2>/dev/null || true
  if [ -n "$APP_ID" ]; then
    /usr/libexec/PlistBuddy -c "Add :SquareApplicationID string $APP_ID" "$PLIST"
    echo "SquareApplicationID set from SQUARE_APPLICATION_ID"
  else
    /usr/libexec/PlistBuddy -c "Add :SquareApplicationID string REPLACE_ME" "$PLIST"
    echo "WARN: SQUARE_APPLICATION_ID unset — AppDelegate will skip MobilePaymentsSDK.initialize"
  fi
fi

# Cap sync should pull FloorSquarePlugin from packages/square-plugin/Package.swift.
# If CapApp-SPM is stale or skipped the local package, inject it (idempotent).
if [ -f "$SPM" ] && ! grep -q "FloorSquarePlugin" "$SPM"; then
  echo "cap sync omitted FloorSquarePlugin; injecting into CapApp-SPM"
  python3 - "$SPM" <<'PY'
from pathlib import Path
import sys
p = Path(sys.argv[1])
text = p.read_text()
if "FloorSquarePlugin" in text:
    raise SystemExit(0)
dep = '        .package(name: "FloorSquarePlugin", path: "../../../../../node_modules/@floor/square-plugin")'
prod = '                .product(name: "FloorSquarePlugin", package: "FloorSquarePlugin")'
# Attach after the last .package( / .product( line inside dependencies / target deps.
import re
m = list(re.finditer(r'^\s*\.package\([^\n]+$', text, re.M))
if not m:
    raise SystemExit("no .package entries in CapApp-SPM")
last = m[-1]
text = text[: last.end()] + ",\n" + dep + text[last.end() :]
m2 = list(re.finditer(r'^\s*\.product\(name: "Cordova"[^\n]+$', text, re.M))
if not m2:
    m2 = list(re.finditer(r'^\s*\.product\([^\n]+$', text, re.M))
if not m2:
    raise SystemExit("no .product entries in CapApp-SPM")
last2 = m2[-1]
text = text[: last2.end()] + ",\n" + prod + text[last2.end() :]
# Bump platform if still v15 (Square needs 16+)
text = text.replace(".iOS(.v15)", ".iOS(.v16)")
p.write_text(text)
print("injected FloorSquarePlugin into CapApp-SPM")
PY
fi

if [ -f "$SPM" ]; then
  grep -q "FloorSquarePlugin" "$SPM" || {
    echo "FloorSquarePlugin still missing from CapApp-SPM after inject" >&2
    exit 1
  }
  grep -q "mobile-payments-sdk-ios\|SquareMobilePaymentsSDK" \
    "$ROOT/packages/square-plugin/Package.swift" || {
    echo "packages/square-plugin/Package.swift missing SquareMobilePaymentsSDK dependency" >&2
    exit 1
  }
  # CapApp-SPM platform must be ≥ 16 for Square's binary target.
  if grep -q '\.iOS(\.v15)' "$SPM"; then
    sed_inplace 's/\.iOS(\.v15)/.iOS(.v16)/g' "$SPM"
    echo "bumped CapApp-SPM platform to iOS 16"
  fi
fi

if [ -f "$CFG" ] && ! grep -q "FloorSquarePlugin" "$CFG"; then
  python3 - "$CFG" <<'PY'
import json, sys
from pathlib import Path
p = Path(sys.argv[1])
data = json.loads(p.read_text())
classes = data.setdefault("packageClassList", [])
if "FloorSquarePlugin" not in classes:
    classes.append("FloorSquarePlugin")
p.write_text(json.dumps(data, indent="\t") + "\n")
print("added FloorSquarePlugin to packageClassList")
PY
fi

# Add Square framework setup as the last Run Script build phase (required by Square).
python3 - "$PBX" <<'PY'
from pathlib import Path
import sys, uuid, re

pbx = Path(sys.argv[1])
text = pbx.read_text()
MARKER = "SquareMobilePaymentsSDK.framework/setup"
if MARKER in text:
    print("Square setup run script already present")
    raise SystemExit(0)

script_id = uuid.uuid4().hex[:24].upper()
build_file_ref = None  # shell script phases don't need PBXBuildFile

phase = f'''\t\t{script_id} /* Square MPSDK Setup */ = {{
\t\t\tisa = PBXShellScriptBuildPhase;
\t\t\talwaysOutOfDate = 1;
\t\t\tbuildActionMask = 2147483647;
\t\t\tfiles = (
\t\t\t);
\t\t\tinputFileListPaths = (
\t\t\t);
\t\t\tinputPaths = (
\t\t\t);
\t\t\tname = "Square MPSDK Setup";
\t\t\toutputFileListPaths = (
\t\t\t);
\t\t\toutputPaths = (
\t\t\t);
\t\t\trunOnlyForDeploymentPostprocessing = 0;
\t\t\tshellPath = /bin/sh;
\t\t\tshellScript = "FRAMEWORKS=\\"${{BUILT_PRODUCTS_DIR}}/${{FRAMEWORKS_FOLDER_PATH}}\\"\\n\\"${{FRAMEWORKS}}/SquareMobilePaymentsSDK.framework/setup\\"\\n";
\t\t}};
'''

# Insert phase definition before /* End PBXShellScriptBuildPhase section */ or after Sources.
if "/* Begin PBXShellScriptBuildPhase section */" in text:
    text = text.replace(
        "/* Begin PBXShellScriptBuildPhase section */\n",
        "/* Begin PBXShellScriptBuildPhase section */\n" + phase,
        1,
    )
else:
    text = text.replace(
        "/* Begin PBXSourcesBuildPhase section */",
        "/* Begin PBXShellScriptBuildPhase section */\n" + phase + "/* End PBXShellScriptBuildPhase section */\n\n/* Begin PBXSourcesBuildPhase section */",
        1,
    )

# Add to App target buildPhases as last entry.
# Find PBXNativeTarget App buildPhases list.
m = re.search(
    r'(isa = PBXNativeTarget;\s+buildConfigurationList = [^;]+;\s+buildPhases = \(\s*)([^)]+)(\);)',
    text,
    re.S,
)
if not m:
    print("WARN: could not find App buildPhases to append Square setup", file=sys.stderr)
else:
    phases = m.group(2).rstrip()
    if script_id not in phases:
        if not phases.endswith("\n"):
            phases = phases + "\n"
        phases = phases + f"\t\t\t\t{script_id} /* Square MPSDK Setup */,\n\t\t\t"
        text = text[: m.start()] + m.group(1) + phases + m.group(3) + text[m.end() :]

pbx.write_text(text)
print("added Square MPSDK Setup run script phase")
PY

echo "PASS  Square iOS prepare complete (SDK via FloorSquarePlugin Package.swift)"
