-- Floor cloud schema. Versioned; do not edit applied files — add 0002+.
-- SKUs are digit strings. Length is settings.sku_digits (currently 5), not a
-- column type, so going to 6 digits is a settings change plus a pad migration.

create table if not exists public.meta (
  key   text primary key,
  value text not null
);

create table if not exists public.settings (
  key   text primary key,
  value jsonb not null
);

create table if not exists public.staff (
  user_id      uuid primary key references auth.users (id) on delete cascade,
  display_name text not null,
  role         text not null default 'staff'
               check (role in ('owner', 'staff')),
  created_at   timestamptz not null default now()
);

create table if not exists public.sku_ledger (
  sku       text primary key
            check (sku ~ '^[0-9]+$'),
  issued_at timestamptz not null,
  label     text not null default '',
  fate      text not null default 'issued'
            check (fate in ('issued', 'sold', 'voided', 'hard-deleted', 'retired'))
);

create table if not exists public.units (
  id                     bigint generated by default as identity primary key,
  sku                    text not null unique references public.sku_ledger (sku),
  brand                  text not null default '',
  model                  text not null default '',
  title                  text not null default '',
  category               text,
  condition              text,
  test_status            text,
  location               text,
  mfr_serial             text,
  defect_notes           text,
  upc                    text,
  lot                    text,
  acquisition_cost_cents integer check (acquisition_cost_cents is null or acquisition_cost_cents >= 0),
  msrp_cents             integer check (msrp_cents is null or msrp_cents >= 0),
  ask_cents              integer check (ask_cents is null or ask_cents >= 0),
  floor_cents            integer check (floor_cents is null or floor_cents >= 0),
  state                  text not null default 'available'
                         check (state in ('available', 'reserved', 'repair', 'sold', 'voided', 'scrapped', 'lost')),
  show_on_website        boolean not null default true,
  received_at            timestamptz not null,
  updated_at             timestamptz not null
);

create index if not exists ix_units_state on public.units (state);
create index if not exists ix_units_brand_model on public.units (brand, model);

create table if not exists public.sales (
  id             bigint generated by default as identity primary key,
  sku            text not null references public.sku_ledger (sku),
  price_cents    integer not null check (price_cents >= 0),
  tax_cents      integer not null default 0 check (tax_cents >= 0),
  channel        text not null,
  payment_method text,
  payment_id     text,
  customer_name  text,
  customer_phone text,
  customer_email text,
  note           text,
  sold_at        timestamptz not null,
  receipt_no     text not null unique,
  actor_id       uuid references auth.users (id),
  voided_at      timestamptz,
  void_reason    text
);

create unique index if not exists ux_one_live_sale_per_sku
  on public.sales (sku) where voided_at is null;

create index if not exists ix_sales_sold_at on public.sales (sold_at);

create table if not exists public.reservations (
  id            uuid primary key default gen_random_uuid(),
  sku           text not null references public.sku_ledger (sku),
  channel       text not null,
  actor_id      uuid references auth.users (id),
  amount_cents  integer,
  payment_id    text,
  created_at    timestamptz not null default now(),
  expires_at    timestamptz not null,
  released_at   timestamptz,
  finalized_at  timestamptz,
  sale_id       bigint references public.sales (id)
);

create unique index if not exists ux_one_live_reservation_per_sku
  on public.reservations (sku)
  where released_at is null and finalized_at is null;

create index if not exists ix_reservations_expires on public.reservations (expires_at)
  where released_at is null and finalized_at is null;

create table if not exists public.events (
  id         bigint generated by default as identity primary key,
  at         timestamptz not null default now(),
  sku        text references public.sku_ledger (sku),
  kind       text not null,
  field      text,
  old_value  text,
  new_value  text,
  actor      text not null default 'floor',
  actor_id   uuid references auth.users (id),
  note       text
);

create index if not exists ix_events_sku_at on public.events (sku, at);

create table if not exists public.photos (
  id            bigint generated by default as identity primary key,
  sku           text not null references public.sku_ledger (sku),
  path          text not null,
  original_path text,
  created_at    timestamptz not null default now(),
  is_primary    boolean not null default false
);

create index if not exists ix_photos_sku on public.photos (sku);

create table if not exists public.listings (
  sku         text not null references public.sku_ledger (sku),
  channel     text not null,
  status      text not null default 'not_listed'
              check (status in ('not_listed', 'listed', 'pending_delist', 'delisted')),
  listing_id  text,
  listed_at   timestamptz,
  delisted_at timestamptz,
  primary key (sku, channel)
);

create table if not exists public.channel_config (
  channel    text primary key,
  mode       text not null default 'off'
             check (mode in ('off', 'manual', 'auto')),
  updated_at timestamptz not null default now()
);

create table if not exists public.delist_tasks (
  id            bigint generated by default as identity primary key,
  sku           text not null references public.sku_ledger (sku),
  channel       text not null,
  sale_id       bigint not null references public.sales (id),
  created_at    timestamptz not null default now(),
  nag_after     timestamptz not null,
  completed_at  timestamptz,
  completed_by  uuid references auth.users (id)
);

create index if not exists ix_delist_open on public.delist_tasks (created_at)
  where completed_at is null;

create table if not exists public.incidents (
  id          bigint generated by default as identity primary key,
  kind        text not null,
  sku         text,
  detail      jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references auth.users (id)
);

create table if not exists public.device_tokens (
  user_id    uuid not null references auth.users (id) on delete cascade,
  token      text not null,
  platform   text not null default 'ios',
  updated_at timestamptz not null default now(),
  primary key (user_id, token)
);

insert into public.meta (key, value) values
  ('schema_version', '1'),
  ('receipt_seq', '0')
on conflict (key) do nothing;

insert into public.settings (key, value) values
  ('storeName', '"Floor"'::jsonb),
  ('skuStart', '10000'::jsonb),
  ('skuDigits', '5'::jsonb),
  ('taxRateBps', '0'::jsonb),
  ('currency', '"USD"'::jsonb),
  ('reservationTtlSeconds', '180'::jsonb),
  ('categories', '["Uncategorized"]'::jsonb),
  ('conditions', '["New","Open box","Excellent","Good","Fair","For parts"]'::jsonb),
  ('testStatuses', '["untested","passed","failed","partial"]'::jsonb),
  ('locations', '["Floor","Back room","Repair bench"]'::jsonb),
  ('channels', '["floor","ebay","facebook","offerup","amazon","tiktok","wholesale"]'::jsonb),
  ('paymentMethods', '["cash","card","other"]'::jsonb)
on conflict (key) do nothing;

insert into public.channel_config (channel, mode) values
  ('floor', 'manual'),
  ('website', 'manual'),
  ('ebay', 'off'),
  ('amazon', 'off'),
  ('facebook', 'off'),
  ('tiktok', 'off')
on conflict (channel) do nothing;

insert into storage.buckets (id, name, public)
values ('unit-photos', 'unit-photos', false)
on conflict (id) do update set public = excluded.public;
