-- Outbox for Resend + APNs. finalize_sale and incidents write here.

create table if not exists public.alert_outbox (
  id         bigint generated by default as identity primary key,
  store_id   uuid not null references public.stores (id) on delete cascade,
  kind       text not null check (kind in ('sale_delist', 'delist_nag', 'double_sell')),
  sku        text,
  payload    jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  sent_at    timestamptz,
  error      text
);

create index if not exists ix_alert_outbox_unsent on public.alert_outbox (created_at)
  where sent_at is null;

alter table public.alert_outbox enable row level security;

create policy manager_alerts on public.alert_outbox for select to authenticated
  using (public.is_store_staff(store_id) and public.is_manager());

create or replace function public.enqueue_sale_alerts(p_sale public.sales)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_manual text[];
begin
  select coalesce(array_agg(l.channel order by l.channel), '{}')
    into v_manual
    from public.listings l
    left join public.channel_config c
      on c.store_id = l.store_id and c.channel = l.channel
   where l.store_id = p_sale.store_id
     and l.sku = p_sale.sku
     and l.status = 'listed'
     and l.channel is distinct from p_sale.channel
     and coalesce(c.mode, 'manual') = 'manual';

  insert into public.alert_outbox (store_id, kind, sku, payload)
  values (
    p_sale.store_id,
    'sale_delist',
    p_sale.sku,
    jsonb_build_object(
      'channel', p_sale.channel,
      'price_cents', p_sale.price_cents,
      'receipt_no', p_sale.receipt_no,
      'pull_from', to_jsonb(v_manual)
    )
  );
end;
$$;

create or replace function public.enqueue_double_sell_alert(p_store uuid, p_sku text, p_detail jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.alert_outbox (store_id, kind, sku, payload)
  values (
    p_store,
    'double_sell',
    p_sku,
    coalesce(p_detail, '{}'::jsonb)
  );
end;
$$;

create or replace function public.enqueue_delist_nags()
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  n int;
begin
  insert into public.alert_outbox (store_id, kind, sku, payload)
  select t.store_id, 'delist_nag', t.sku,
         jsonb_build_object('channel', t.channel, 'task_id', t.id, 'nag_after', t.nag_after)
    from public.delist_tasks t
   where t.completed_at is null
     and t.nag_after <= now()
     and not exists (
       select 1 from public.alert_outbox o
        where o.kind = 'delist_nag'
          and o.sku = t.sku
          and o.store_id = t.store_id
          and o.payload->>'task_id' = t.id::text
          and o.created_at > t.nag_after
     );
  get diagnostics n = row_count;
  return n;
end;
$$;

-- Patch finalize_sale / incident inserts to enqueue alerts.
create or replace function public.finalize_sale(
  p_sku text,
  p_channel text,
  p_price_cents int,
  p_payment_method text default null,
  p_payment_id text default null,
  p_customer_name text default null,
  p_customer_phone text default null,
  p_customer_email text default null,
  p_note text default null,
  p_reservation_id uuid default null,
  p_tax_cents int default 0,
  p_approval_id uuid default null
)
returns public.sales
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale public.sales;
  v_receipt text;
  v_seq int;
  v_store uuid := public.current_store_id();
  v_floor int;
begin
  perform public.assert_staff_or_service();
  perform public.release_expired_reservations();

  if v_store is null then
    select store_id into v_store from public.units where sku = p_sku limit 1;
  end if;
  if v_store is null then
    raise exception 'no_store' using errcode = 'P0001';
  end if;

  if p_price_cents is null or p_price_cents < 0 then
    raise exception 'invalid_price' using errcode = '22023';
  end if;
  if p_channel is null or btrim(p_channel) = '' then
    raise exception 'invalid_channel' using errcode = '22023';
  end if;

  select floor_cents into v_floor
    from public.units
   where sku = p_sku and store_id = v_store;
  if v_floor is not null and p_price_cents < v_floor then
    if p_approval_id is null or not exists (
      select 1 from public.approvals a
       where a.id = p_approval_id
         and a.store_id = v_store
         and a.action = 'below_floor'
         and a.sku = p_sku
         and a.consumed_at is null
         and a.created_at > now() - interval '10 minutes'
    ) then
      raise exception 'below_floor' using errcode = 'P0001';
    end if;
    update public.approvals set consumed_at = now() where id = p_approval_id;
  end if;

  if p_reservation_id is not null then
    update public.reservations
       set payment_id = coalesce(p_payment_id, payment_id)
     where id = p_reservation_id
       and sku = p_sku
       and store_id = v_store
       and released_at is null
       and finalized_at is null
       and expires_at > now();
    if not found then
      raise exception 'reservation_expired' using errcode = 'P0001';
    end if;
  end if;

  update public.units
     set state = 'sold', updated_at = now()
   where sku = p_sku
     and store_id = v_store
     and state in ('available', 'reserved');
  if not found then
    insert into public.incidents (store_id, kind, sku, detail)
    values (
      v_store,
      'double_sell',
      p_sku,
      jsonb_build_object('channel', p_channel, 'payment_id', p_payment_id)
    );
    perform public.enqueue_double_sell_alert(
      v_store, p_sku, jsonb_build_object('channel', p_channel, 'payment_id', p_payment_id)
    );
    raise exception 'unit_not_sellable' using errcode = 'P0001';
  end if;

  insert into public.store_settings (store_id, key, value)
  values (v_store, 'receipt_seq', '0'::jsonb)
  on conflict (store_id, key) do nothing;

  update public.store_settings
     set value = to_jsonb(coalesce((value #>> '{}')::int, 0) + 1)
   where store_id = v_store and key = 'receipt_seq'
  returning (value #>> '{}')::int into v_seq;
  v_receipt := 'R-' || lpad(v_seq::text, greatest(5, public.sku_digits()), '0');

  begin
    insert into public.sales (
      store_id, sku, price_cents, tax_cents, channel, payment_method, payment_id,
      customer_name, customer_phone, customer_email, note, sold_at, receipt_no, actor_id
    ) values (
      v_store, p_sku, p_price_cents, coalesce(p_tax_cents, 0), btrim(p_channel), p_payment_method, p_payment_id,
      p_customer_name, p_customer_phone, p_customer_email, p_note, now(), v_receipt, auth.uid()
    )
    returning * into v_sale;
  exception
    when unique_violation then
      insert into public.incidents (store_id, kind, sku, detail)
      values (
        v_store,
        'double_sell',
        p_sku,
        jsonb_build_object('channel', p_channel, 'payment_id', p_payment_id)
      );
      perform public.enqueue_double_sell_alert(
        v_store, p_sku, jsonb_build_object('channel', p_channel, 'payment_id', p_payment_id)
      );
      raise;
  end;

  update public.sku_ledger set fate = 'sold' where sku = p_sku and store_id is not distinct from v_store;

  if p_reservation_id is not null then
    update public.reservations
       set finalized_at = now(), sale_id = v_sale.id, payment_id = coalesce(p_payment_id, payment_id)
     where id = p_reservation_id;
  else
    update public.reservations
       set released_at = now()
     where store_id = v_store and sku = p_sku and released_at is null and finalized_at is null;
  end if;

  insert into public.events (store_id, sku, kind, new_value, actor, actor_id, note)
  values (
    v_store,
    p_sku,
    'sold',
    p_price_cents::text,
    coalesce((select display_name from public.staff where user_id = auth.uid()), 'service'),
    auth.uid(),
    btrim(p_channel) || ' ' || v_receipt
  );

  perform public.open_delist_tasks(v_sale);
  perform public.enqueue_sale_alerts(v_sale);
  return v_sale;
end;
$$;

create or replace function public.claim_alerts(p_limit int default 50)
returns setof public.alert_outbox
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() <> 'service_role' then
    raise exception 'not_service' using errcode = '42501';
  end if;
  return query
    update public.alert_outbox o
       set sent_at = now()
     where o.id in (
       select id from public.alert_outbox
        where sent_at is null
        order by created_at
        limit p_limit
       for update skip locked
     )
    returning *;
end;
$$;

-- claim_alerts marks sent immediately which is wrong if send fails.
-- Use peek + mark instead.
create or replace function public.peek_alerts(p_limit int default 50)
returns setof public.alert_outbox
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() <> 'service_role' then
    raise exception 'not_service' using errcode = '42501';
  end if;
  return query
    select * from public.alert_outbox
     where sent_at is null
     order by created_at
     limit p_limit;
end;
$$;

create or replace function public.mark_alert_sent(p_id bigint, p_error text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() <> 'service_role' then
    raise exception 'not_service' using errcode = '42501';
  end if;
  update public.alert_outbox
     set sent_at = case when p_error is null then now() else sent_at end,
         error = p_error
   where id = p_id;
end;
$$;

do $$
begin
  perform 1 from pg_extension where extname = 'pg_cron';
  if found then
    perform cron.schedule(
      'floor-delist-nags',
      '*/5 * * * *',
      'select public.enqueue_delist_nags()'
    );
  end if;
exception
  when others then
    raise notice 'pg_cron not available for delist nags; Netlify schedule will call enqueue';
end;
$$;

grant execute on function public.peek_alerts(int) to service_role;
grant execute on function public.mark_alert_sent(bigint, text) to service_role;
grant execute on function public.enqueue_delist_nags() to service_role;
