begin;

alter table public.units add column if not exists listed_on text[] not null default '{}'::text[];
alter table public.web_orders add column if not exists ship_by date;

create table if not exists public.google_sync_queue (
  store_id uuid not null references public.stores(id) on delete cascade,
  sku text not null,
  action text not null default 'upsert' check (action in ('upsert','delete')),
  attempts int not null default 0,
  last_error text,
  queued_at timestamptz not null default now(),
  primary key (store_id, sku)
);
alter table public.google_sync_queue enable row level security;
revoke all on public.google_sync_queue from public, anon, authenticated;
grant all on public.google_sync_queue to service_role;
create table if not exists public.google_product_index (
  store_id uuid not null references public.stores(id) on delete cascade,
  sku text not null,
  updated_at timestamptz not null default now(),
  primary key(store_id,sku)
);
alter table public.google_product_index enable row level security;
revoke all on public.google_product_index from public,anon,authenticated;
grant all on public.google_product_index to service_role;

create table if not exists public.marketplace_email_sales (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  message_id text not null,
  marketplace text,
  subject text,
  state text not null default 'needs_review' check (state in ('ignored','needs_review','matched','failed')),
  sku text,
  item_title text,
  order_number text,
  sale_price_cents int,
  ship_by date,
  fulfillment text,
  buyer jsonb not null default '{}'::jsonb,
  confidence numeric(5,4),
  sale_id bigint references public.sales(id),
  reason text,
  created_at timestamptz not null default now(),
  unique (store_id, message_id)
);
alter table public.marketplace_email_sales enable row level security;
revoke all on public.marketplace_email_sales from public, anon, authenticated;
grant all on public.marketplace_email_sales to service_role;
create index if not exists marketplace_email_sales_review on public.marketplace_email_sales(store_id,created_at desc) where state='needs_review';

create or replace function public.queue_google_unit(p_store uuid,p_sku text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if p_store is null or nullif(btrim(p_sku),'') is null then return; end if;
  insert into public.google_sync_queue(store_id,sku) values(p_store,btrim(p_sku))
  on conflict(store_id,sku) do update set action='upsert',attempts=0,last_error=null,queued_at=now();
end $$;

create or replace function public.queue_google_unit_trigger()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  perform public.queue_google_unit(coalesce(new.store_id,old.store_id),coalesce(new.sku,old.sku));
  if tg_op='UPDATE' and (old.store_id,old.sku) is distinct from (new.store_id,new.sku) then
    perform public.queue_google_unit(old.store_id,old.sku);
  end if;
  if tg_op='DELETE' then return old; end if;
  return new;
end $$;

drop trigger if exists google_queue_units on public.units;
create trigger google_queue_units after insert or update of state,show_on_website,ask_cents,title,brand,model,condition,defect_notes,upc,package_length_in,package_width_in,package_height_in,package_weight_lb,listing_body on public.units
for each row execute function public.queue_google_unit_trigger();
drop trigger if exists google_queue_photos on public.photos;
create trigger google_queue_photos after insert or update or delete on public.photos
for each row execute function public.queue_google_unit_trigger();

create or replace function public.portal_marketplace_email_sales()
returns setof public.marketplace_email_sales language plpgsql stable security definer set search_path=public as $$
declare v_store uuid:=public.portal_store_id();
begin
  if v_store is null then raise exception 'portal_access_denied' using errcode='42501'; end if;
  return query select * from public.marketplace_email_sales where store_id=v_store order by created_at desc limit 200;
end $$;
revoke all on function public.portal_marketplace_email_sales() from public,anon;
grant execute on function public.portal_marketplace_email_sales() to authenticated;

create or replace function public.portal_marketplace_inventory()
returns table(sku text,title text,listed_on text[],state text,ask_cents int,has_photo boolean)
language plpgsql stable security definer set search_path=public as $$
declare v_store uuid:=public.portal_store_id();
begin
  if v_store is null then raise exception 'portal_access_denied' using errcode='42501'; end if;
  return query select u.sku,u.title,u.listed_on,u.state,u.ask_cents,
    exists(select 1 from public.photos p where p.store_id=u.store_id and p.sku=u.sku)
  from public.units u where u.store_id=v_store and (u.state='available' or cardinality(coalesce(u.listed_on,'{}'))>0)
  order by u.sku;
end $$;
revoke all on function public.portal_marketplace_inventory() from public,anon;
grant execute on function public.portal_marketplace_inventory() to authenticated;
create or replace function public.portal_web_orders(p_days int default 90)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare v_store uuid:=public.portal_store_id();
begin
  if v_store is null then raise exception 'portal_access_denied' using errcode='42501'; end if;
  return coalesce((select jsonb_agg(x order by x.created_at desc) from (
    select o.id,o.order_no,o.sku,o.status,o.fulfillment,o.channel,o.buyer_name,o.buyer_email,o.buyer_phone,
      o.ship_line1,o.ship_line2,o.ship_city,o.ship_region,o.ship_postal,o.item_cents,o.shipping_cents,o.tax_cents,o.total_cents,
      o.payment_id,o.refund_id,o.payment_env,o.created_at,o.paid_at,o.pickup_deadline,o.picked_up_at,o.picked_up_by,
      o.boxed_at,o.shipped_at,o.tracking_number,o.tracking_url,o.carrier,o.service,o.shipping_rate,o.label_url,
      o.label_purchased_at,o.label_cost_cents,o.refund_requested_at,o.cancel_source,o.cancel_reason,o.canceled_at,o.ship_by,
      coalesce(nullif(btrim(u.title),''),nullif(btrim(concat_ws(' ',u.brand,u.model)),''),'Item') as title,
      jsonb_build_object('length_in',u.package_length_in,'width_in',u.package_width_in,'height_in',u.package_height_in,'weight_lb',u.package_weight_lb) as package
    from public.web_orders o left join public.units u on u.store_id=o.store_id and u.sku=o.sku
    where o.store_id=v_store and o.created_at>now()-make_interval(days=>greatest(p_days,1))
      and (o.status in ('paid','refunded') or o.paid_at is not null)
  ) x),'[]'::jsonb);
end $$;
revoke all on function public.portal_web_orders(int) from public,anon;
grant execute on function public.portal_web_orders(int) to authenticated;

create or replace function public.portal_marketplace_delists()
returns table(id bigint,sku text,channel text,created_at timestamptz,nag_after timestamptz,attempts int,last_error text)
language plpgsql stable security definer set search_path=public as $$
declare v_store uuid:=public.portal_store_id();
begin
  if v_store is null then raise exception 'portal_access_denied' using errcode='42501'; end if;
  return query select d.id,d.sku,d.channel,d.created_at,d.nag_after,d.attempts,d.last_error from public.delist_tasks d
    where d.store_id=v_store and d.completed_at is null and d.channel<>'ebay' order by d.created_at desc limit 200;
end $$;
revoke all on function public.portal_marketplace_delists() from public,anon;
grant execute on function public.portal_marketplace_delists() to authenticated;

create or replace function public.portal_vendoo_export()
returns table(sku text,title text,description text,price_cents int,condition text,brand text,category text,model text,photo_paths text[],package_weight_lb numeric,package_length_in numeric,package_width_in numeric,package_height_in numeric,listed_on text[])
language plpgsql stable security definer set search_path=public as $$
declare v_store uuid:=public.portal_store_id();
begin
  if v_store is null then raise exception 'portal_access_denied' using errcode='42501'; end if;
  return query
  select u.sku,left(coalesce(nullif(btrim(u.ebay_title),''),nullif(btrim(u.title),''),concat_ws(' ',u.brand,u.model)),80),
    concat_ws(E'\n\n',nullif(btrim(u.ai_description),''),nullif(btrim(u.listing_body),''),concat_ws(E'\n','Condition: '||coalesce(nullif(u.condition,''),'See photos'),nullif(u.defect_notes,''),'SKU '||u.sku)),
    u.ask_cents,u.condition,u.brand,u.category,u.model,
    coalesce((select array_agg(p.path order by p.is_primary desc,p.sort_order,p.id) from public.photos p where p.store_id=u.store_id and p.sku=u.sku),'{}'::text[]),
    u.package_weight_lb,u.package_length_in,u.package_width_in,u.package_height_in,u.listed_on
  from public.units u where u.store_id=v_store and u.state='available' and u.show_on_website
    and u.ask_cents>0 and exists(select 1 from public.photos p where p.store_id=u.store_id and p.sku=u.sku)
    and not ('vendoo'=any(u.listed_on)) order by u.sku;
end $$;
revoke all on function public.portal_vendoo_export() from public,anon;
grant execute on function public.portal_vendoo_export() to authenticated;

create or replace function public.portal_set_unit_listed_on(p_sku text,p_channels text[])
returns text[] language plpgsql security definer set search_path=public as $$
declare v_store uuid:=public.portal_store_id(); v_channels text[];
begin
  if v_store is null then raise exception 'portal_access_denied' using errcode='42501'; end if;
  select coalesce(array_agg(distinct lower(btrim(x)) order by lower(btrim(x))),'{}'::text[]) into v_channels
  from unnest(coalesce(p_channels,'{}'::text[])) x
  where lower(btrim(x)) in ('vendoo','mercari','poshmark','facebook','depop','other');
  update public.units set listed_on=v_channels,updated_at=now() where store_id=v_store and sku=p_sku;
  if not found then raise exception 'unit_not_found' using errcode='P0002'; end if;
  update public.listings set status='delisted',delisted_at=now()
    where store_id=v_store and sku=p_sku and channel in ('vendoo','mercari','poshmark','facebook','depop','other')
      and not(channel=any(v_channels)) and status='listed';
  insert into public.listings(store_id,sku,channel,status,listed_at,delisted_at)
    select v_store,p_sku,x,'listed',now(),null from unnest(v_channels) x
    on conflict(store_id,sku,channel) do update set status='listed',listed_at=coalesce(public.listings.listed_at,now()),delisted_at=null;
  return v_channels;
end $$;
revoke all on function public.portal_set_unit_listed_on(text,text[]) from public,anon;
grant execute on function public.portal_set_unit_listed_on(text,text[]) to authenticated;

create or replace function public.marketplace_ingest_sale(p_store uuid,p_sku text,p_channel text,p_price_cents int,p_order_number text,p_message_id text,p_marketplace text,p_item_title text,p_ship_by date,p_fulfillment text,p_buyer jsonb,p_confidence numeric)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_sale public.sales; v_existing bigint; v_unit public.units;
begin
  perform public.assert_service();
  if lower(p_channel) not in ('mercari','poshmark','facebook','depop','other') then raise exception 'invalid_marketplace'; end if;
  select sale_id into v_existing from public.marketplace_email_sales where store_id=p_store and message_id=p_message_id;
  if v_existing is not null then return v_existing; end if;
  select * into v_unit from public.units where store_id=p_store and sku=p_sku for update;
  if not found or v_unit.state<>'available' then raise exception 'unit_not_available'; end if;
  update public.listings set status='delisted',delisted_at=now() where store_id=p_store and sku=p_sku and channel=p_channel;
  v_sale:=public.finalize_sale(p_sku=>p_sku,p_channel=>p_channel,p_price_cents=>p_price_cents,p_payment_method=>'marketplace',
    p_payment_id=>'marketplace:'||p_marketplace||':'||coalesce(p_order_number,p_message_id),p_note=>'Marketplace order '||coalesce(p_order_number,p_message_id));
  insert into public.marketplace_email_sales(store_id,message_id,marketplace,state,sku,item_title,order_number,sale_price_cents,ship_by,fulfillment,buyer,confidence,sale_id)
  values(p_store,p_message_id,p_marketplace,'matched',p_sku,p_item_title,p_order_number,p_price_cents,p_ship_by,p_fulfillment,coalesce(p_buyer,'{}'::jsonb),p_confidence,v_sale.id)
  on conflict(store_id,message_id) do update set state='matched',sale_id=excluded.sale_id,sku=excluded.sku,reason=null;
  insert into public.web_orders(store_id,sku,sale_id,status,fulfillment,buyer_name,buyer_email,buyer_phone,
    ship_line1,ship_line2,ship_city,ship_region,ship_postal,ship_country,item_cents,shipping_cents,tax_cents,total_cents,
    payment_id,created_at,updated_at,order_no,paid_at,payment_env,channel,ship_by)
  values(p_store,p_sku,v_sale.id,'paid',case when p_fulfillment='pickup' then 'pickup' else 'ship' end,
    p_buyer->>'name',p_buyer->>'email',p_buyer->>'phone',p_buyer->>'line1',p_buyer->>'line2',p_buyer->>'city',
    p_buyer->>'region',p_buyer->>'postal',coalesce(p_buyer->>'country','US'),p_price_cents,0,0,p_price_cents,
    'marketplace:'||p_marketplace||':'||coalesce(p_order_number,p_message_id),now(),now(),
    upper(p_marketplace)||'-'||left(regexp_replace(coalesce(p_order_number,p_message_id),'[^A-Za-z0-9-]','','g'),32),now(),'production',lower(p_channel),p_ship_by)
  on conflict do nothing;
  return v_sale.id;
end $$;
revoke all on function public.marketplace_ingest_sale(uuid,text,text,int,text,text,text,text,date,text,jsonb,numeric) from public,anon,authenticated;
grant execute on function public.marketplace_ingest_sale(uuid,text,text,int,text,text,text,text,date,text,jsonb,numeric) to service_role;

create or replace function public.portal_complete_marketplace_delist(p_id bigint)
returns void language plpgsql security definer set search_path=public as $$
declare v_store uuid:=public.portal_store_id();
begin
  if v_store is null then raise exception 'portal_access_denied' using errcode='42501'; end if;
  update public.delist_tasks set completed_at=now(),completed_by=auth.uid()
  where id=p_id and store_id=v_store and channel<>'ebay' and completed_at is null;
end $$;
revoke all on function public.portal_complete_marketplace_delist(bigint) from public,anon;
grant execute on function public.portal_complete_marketplace_delist(bigint) to authenticated;

update public.store_settings
set value=coalesce((select jsonb_agg(to_jsonb(lower(btrim(x)))) from jsonb_array_elements_text(value) x where lower(btrim(x))<>'ebay'),'[]'::jsonb)
where key='online_channels' and jsonb_typeof(value)='array';
update public.store_settings set value='true'::jsonb where key='ebay_disabled';
insert into public.store_settings(store_id,key,value) select id,'google_merchant_enabled','false'::jsonb from public.stores on conflict(store_id,key) do nothing;
update public.listings set status='delisted',delisted_at=coalesce(delisted_at,now())
where channel='ebay' and status in ('listed','pending_delist');
update public.delist_tasks set completed_at=coalesce(completed_at,now())
where channel='ebay' and completed_at is null;

select (select count(*) from public.google_sync_queue) as google_queue,
       (select count(*) from public.marketplace_email_sales where state='needs_review') as marketplace_reviews,
       (select count(*) from public.listings where channel='ebay' and status in ('listed','pending_delist')) as ebay_active_rows;

commit;
