create or replace function public.tg_customers_welcome() returns trigger language plpgsql security definer set search_path = public as $$ begin if NEW.email is not null then insert into public.email_outbox (store_id, customer_id, kind, to_email) values (NEW.store_id, NEW.id, 'welcome', NEW.email); end if; return NEW; end; $$;
drop trigger if exists customers_welcome on public.customers;
create trigger customers_welcome after insert on public.customers for each row execute function public.tg_customers_welcome();
create or replace function public.tg_ledger_points_email() returns trigger language plpgsql security definer set search_path = public as $$ declare v_email text; v_unsub timestamptz; begin if NEW.reason <> 'earn_sale' then return NEW; end if; select email, unsubscribed_at into v_email, v_unsub from public.customers where id = NEW.customer_id; if v_email is null or v_unsub is not null then return NEW; end if; insert into public.email_outbox (store_id, customer_id, kind, to_email, payload) values (NEW.store_id, NEW.customer_id, 'points', v_email, jsonb_build_object('earned', NEW.delta, 'balance', NEW.balance_after, 'ticket_id', NEW.ticket_id)); return NEW; end; $$;
drop trigger if exists ledger_points_email on public.customer_points_ledger;
create trigger ledger_points_email after insert on public.customer_points_ledger for each row execute function public.tg_ledger_points_email();
revoke all on function public.lookup_customer_by_phone(text) from public, anon;
revoke all on function public.upsert_customer(text, text, text, boolean) from public, anon;
revoke all on function public.customer_points_balance(uuid) from public, anon;
revoke all on function public.customer_points_history(uuid, int) from public, anon;
revoke all on function public.list_customers(text, int) from public, anon;
revoke all on function public.adjust_customer_points(uuid, int, text) from public, anon;
revoke all on function public.queue_loyalty_campaign(text, text, int, int) from public, anon;
revoke all on function public.web_lookup_customer(uuid, text) from public, anon, authenticated;
revoke all on function public.web_upsert_customer(uuid, text, text, text, boolean) from public, anon, authenticated;
revoke all on function public.unsubscribe_loyalty(uuid) from public, anon, authenticated;
revoke all on function public.claim_email_outbox(int) from public, anon, authenticated;
revoke all on function public.finish_email_outbox(bigint, boolean, text) from public, anon, authenticated;
grant execute on function public.lookup_customer_by_phone(text) to authenticated, service_role;
grant execute on function public.upsert_customer(text, text, text, boolean) to authenticated, service_role;
grant execute on function public.customer_points_balance(uuid) to authenticated, service_role;
grant execute on function public.customer_points_history(uuid, int) to authenticated, service_role;
grant execute on function public.list_customers(text, int) to authenticated, service_role;
grant execute on function public.adjust_customer_points(uuid, int, text) to authenticated, service_role;
grant execute on function public.queue_loyalty_campaign(text, text, int, int) to authenticated, service_role;
grant execute on function public.web_lookup_customer(uuid, text) to service_role;
grant execute on function public.web_upsert_customer(uuid, text, text, text, boolean) to service_role;
grant execute on function public.unsubscribe_loyalty(uuid) to service_role;
grant execute on function public.claim_email_outbox(int) to service_role;
grant execute on function public.finish_email_outbox(bigint, boolean, text) to service_role;
grant usage, select on sequence public.email_outbox_id_seq to service_role;;
