begin;

-- These two high SKUs were generated by disposable AI-scan smoke tests, then
-- their units were deleted. The portal's next-SKU calculation still sees their
-- ledger rows and otherwise reports the five-digit range exhausted.
delete from public.sku_ledger l
where (l.sku='99998' and l.label='Dawn Ultra Original Liquid Dish Soap, 18 fl oz'
       or l.sku='99999' and l.label='Ninja Professional Blender (BL610)')
  and l.fate='hard-deleted'
  and not exists(select 1 from public.units u where u.store_id=l.store_id and u.sku=l.sku)
  and not exists(select 1 from public.sales s where s.store_id=l.store_id and s.sku=l.sku)
  and not exists(select 1 from public.events e where e.store_id=l.store_id and e.sku=l.sku);

commit;
